# Exploratory Data Anlaysis of 2024 ANES DATA

In [1]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv
load_dotenv(override=True)

True

In [2]:
data_path = os.getenv("ANES_DATA_PATH")
anes_24 = pd.read_csv(data_path, low_memory=False)

In [3]:
anes_24.describe()

,V240001,V200001,V160001_orig,V240002a,V240002b,V240002c,V240003,V240107a,V240107c,V240107d,...,V245008,V245009,V245011,V245012,V245013,V245014,V245015,V245016,V245017,V245018
count,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,...,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000,5521.000000
mean,214468.828473,85779.698424,149691.869408,1.896939,1.426915,1.899112,1.795508,1.000000,24.911610,69.830647,...,-0.685745,-0.603333,250.426191,-0.858721,-1.164825,-0.977359,-0.568556,-0.796595,-0.704583,-0.698605
std,77453.441194,106769.551324,187910.024862,0.513647,2.660526,0.301207,0.735011,1.054148,65.369314,36.675315,...,0.683099,0.954328,657.642506,2.075207,1.648452,1.863171,2.637257,0.483529,0.681161,0.790166
min,140001.000000,-1.000000,-1.000000,1.000000,-7.000000,1.000000,1.000000,0.045193,1.000000,1.000000,...,-1.000000,-1.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-1.000000,-1.000000,-1.000000
25%,141692.000000,-1.000000,-1.000000,2.000000,2.000000,2.000000,1.000000,0.358461,1.000000,33.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
50%,210620.000000,-1.000000,-1.000000,2.000000,2.000000,2.000000,2.000000,0.612811,2.000000,72.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
75%,234292.000000,213172.000000,401400.000000,2.000000,2.000000,2.000000,2.000000,1.177523,20.000000,101.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
max,399909.000000,236427.000000,407791.000000,4.000000,5.000000,2.000000,3.000000,5.000000,425.000000,134.000000,...,1.000000,3.000000,2000.000000,4.000000,2.000000,2.000000,9.000000,1.000000,1.000000,3.000000

In [4]:
anes_issue_mapping = {
    "Defense Spending": "V241242",
    "Israel/Palestine": "V241409x",
    "Terrorism": "V242343",
    "Free Trade" : "V242346x",
    "Protection of American Jobs": "V242226x",
    "China": "V242365",
    "Environment": "V241260",
    "School funding": "V241266x",
    "Health care": "V242353x", # can be combination of V242351 and V242352
    "Welfare": "V241275x", # can be combination of V241273  and V241274
    "Aid to the poor": "V241281x", # can be combination of V241279 and V241280
    "Income Inequality": "V242252",
    "Employment/Income": "V241252",
    "Social Security": "V241263x",
    "Cost of living": "V242173",
    "Crime": "V241272x", # can be combination of V241270 and V241271
    "Race relations": "V242349x", # can be combination of V242347 and V242348
    "Opioid Crisis": "V242335x", # can be combination of V242334 and V242335
    "Policing": "V241397",
    "Gun Control": "V242328x", # can be combination of V242326 and V242327
    "Corruption": "V242456",
    "Budget deficit": "V242315",
    "Tax on the rich": "V242316b",
    "Immigration": "V242227",
    "Campaign spending": "V242214",
    "Separation of powers in government": "V241325",
    "Economy": "V241236", # note this asks who does better job (Democrat or Republican) on the economy, biased by partisan politics
    "Science": "V242420",
    "Invested in stock market": "V241554",
    "Building/repairing highways": "V241278x",
    "Abortion": "V241248",
    "Traditional family values": "V242259",
    "LGB rights": "V241379", # can be combination of V241379 and V241380
    "Transgender rights": "V241375x",
    "Traditional media": "V242422",
    "Social media": "V242423",
    "Sexism": "V242281",
    "Sexual Harrassment": "V242361x",
    "Voter ID": "V241319x",
    "Religion": "V241420",
}

In [5]:
anes_24_issues = anes_24[list(anes_issue_mapping.values())]
anes_24_issues = anes_24_issues.rename(columns={v: k for k, v in anes_issue_mapping.items()})

In [6]:
anes_24_issues.head()

,Defense Spending,Israel/Palestine,Terrorism,Free Trade,Protection of American Jobs,China,Environment,School funding,Health care,Welfare,...,Abortion,Traditional family values,LGB rights,Transgender rights,Traditional media,Social media,Sexism,Sexual Harrassment,Voter ID,Religion
0,5,1,3,2,2,5,6,3,6,5,...,4,2,2,1,4,3,5,5,1,2
1,4,8,3,4,3,4,6,1,4,3,...,1,4,1,3,4,4,4,3,3,5
2,1,4,4,4,4,3,7,1,1,1,...,1,5,1,7,2,3,5,5,6,5
3,99,8,1,2,4,4,1,1,4,3,...,5,2,1,7,2,3,2,3,2,1
4,3,4,3,7,1,4,4,5,7,3,...,6,2,2,1,4,2,2,3,1,3

In [7]:
for i in anes_issue_mapping.values():
    print(i)

V241242
V241409x
V242343
V242346x
V242226x
V242365
V241260
V241266x
V242353x
V241275x
V241281x
V242252
V241252
V241263x
V242173
V241272x
V242349x
V242335x
V241397
V242328x
V242456
V242315
V242316b
V242227
V242214
V241325
V241236
V242420
V241554
V241278x
V241248
V242259
V241379
V241375x
V242422
V242423
V242281
V242361x
V241319x
V241420

In [8]:
extraneous_responses = {
    -9: "Refused",
    -8: "Don't know",
    -7: "Insuﬃcient partial, interview deleted",
    -6: "No post interview",
    -5: "Suﬃcient partial, breakoﬀ",
    -4: "Error",
    -3: "RESTRICTED",
    -2: "DK/RF in V241407 or V241408",
    -1: "Inapplicable",
    95: "Haven't heard of left-right",
    96: "Do not know enough about party",
    97: "Do not know enough about candidate",
    98: "Refused (VOL)",
    99: "Haven't though much about this",
    998: "Don’t know (where to rate)",
    999: "Dont recognize"
}

In [9]:
# Replace extraneous responses with NaN
anes_24_issues.replace(extraneous_responses.keys(), np.nan, inplace=True)

# Make number 8 (side with neither) into 4 (side with both equally) for isreal/palestine
anes_24_issues['Israel/Palestine'] = anes_24_issues['Israel/Palestine'].replace(8, 4)

# For campaign spending swap 2 and 3 values since 3 is 'neither favor or oppose' and 2 is 'oppose' and 1 is 'favor'
anes_24_issues['Campaign spending'] = anes_24_issues['Campaign spending'].replace({2: 3, 3: 2})

anes_24_issues.head()

,Defense Spending,Israel/Palestine,Terrorism,Free Trade,Protection of American Jobs,China,Environment,School funding,Health care,Welfare,...,Abortion,Traditional family values,LGB rights,Transgender rights,Traditional media,Social media,Sexism,Sexual Harrassment,Voter ID,Religion
0,5.0,1.0,3.0,2.0,2.0,5.0,6.0,3.0,6.0,5.0,...,4.0,2.0,2.0,1.0,4.0,3.0,5.0,5.0,1.0,2.0
1,4.0,4.0,3.0,4.0,3.0,4.0,6.0,1.0,4.0,3.0,...,1.0,4.0,1.0,3.0,4.0,4.0,4.0,3.0,3.0,5.0
2,1.0,4.0,4.0,4.0,4.0,3.0,7.0,1.0,1.0,1.0,...,1.0,5.0,1.0,7.0,2.0,3.0,5.0,5.0,6.0,5.0
3,NaN,4.0,1.0,2.0,4.0,4.0,1.0,1.0,4.0,3.0,...,5.0,2.0,1.0,7.0,2.0,3.0,2.0,3.0,2.0,1.0
4,3.0,4.0,3.0,7.0,1.0,4.0,4.0,5.0,7.0,3.0,...,6.0,2.0,2.0,1.0,4.0,2.0,2.0,3.0,1.0,3.0